trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
  DOTNET_SDK_VERSION: '3.1.201'

pool:
  name: Global Roam Office Build-03

resources:
  repositories:
    - repository: templates
      type: github
      name: global-roam/devops-pipelines
      endpoint: global-roam

steps:
  - checkout: self
    clean: true

  - template: pipelines/common/authenticate/jobs/steps/nuget-and-npm.pipeline.yml@templates

  - template: pipelines/common/workarounds/jobs/steps/pr-workaround-branch.pipeline.yml@templates
  
  - task: DotNetCoreInstaller@1
    displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
    inputs:
      version: '$(DOTNET_SDK_VERSION)'

  - task: CmdLine@2
    displayName: 'Build and publish package'
    inputs:
      script: './build.cmd Push -ArtifactsDirectory $(Build.ArtifactStagingDirectory) -TestResutsDirectory $(Common.TestResultsDirectory)'
    env:
      AZURE_DEVOPS_TOKEN: $(System.AccessToken)
      ApplicationId: $(Production-client-id)
      ApplicationPassword: $(Production-client-secret)
      CertificateName: Global-Roam-Code-Signing

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx'
      searchFolder: $(Common.TestResultsDirectory)
      mergeTestResults: true
    condition: and(always(), not(canceled()))
    continueOnError: true

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Common.TestResultsDirectory)/coverage.cobertura.xml
      
  - template: pipelines/common/workarounds/jobs/steps/pr-workaround-cleanup.pipeline.yml@templates

